name: cli-commander-fake-names-generator

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron:  '0 1 * * *'

jobs:
  lintandtest:
    uses: ./.github/workflows/lint_and_test.yaml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [16.x, 18.x, 20.x]

  build:
    runs-on: ${{ matrix.os }}
    needs: lintandtest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [16.x, 18.x, 20.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install
        run: npm install
      - name: npm run build
        working-directory: .
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            dist/
            build/
  

  