name: Lint and Test
 
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '18'
        type: string
      os-version:
        required: false
        default: '18'
        type: string
      working-directory:
        required: false
        default: '.'
        type: string
 
jobs:
  lint-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs['node-version'] }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ inputs['node-version'] }}
            cache: 'npm'
            cache-dependency-path: ${{ inputs['working-directory'] }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs['working-directory'] }}
        run: npm ci

      - name: Run lint
        working-directory: ${{ inputs['working-directory'] }}
        run: npm run lint

      - name: Run tests
        working-directory: ${{ inputs['working-directory'] }}
        run: npm test